from pathlib import Path

SDK_VERSION = "1.4.3"

MAX_N_PARAMS = 4
MAX_N_CATEGORICAL_VALUES = 20
MAX_N_CATEGORICAL_LABEL_CHARS = 20
MAX_N_AUDIO_SAMPLES = 3

DEFAULT_DAW_SR = 48000
DEFAULT_DAW_BS = 2048

NEUTONE_GEN_N_NUMERICAL_PARAMS = 4
NEUTONE_GEN_N_TEXT_PARAMS = 1
NEUTONE_GEN_N_TOKENS_PARAMS = 1
